version: '3.8'

services:
  rtvt_backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - ssh_username=${ssh_username}
      - ssh_password=${ssh_password}
      - ssh_hostname=${ssh_hostname}
      - ssh_port=${ssh_port}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - SSH=${SSH}
    ports:
      - "8000:8000"
