version: '3.8'

services:
  mlcb_backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: ${DOCKER_USERNAME}/mlcb:backend
    platform: linux/amd64
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - ssh_username=${ssh_username}
      - ssh_password=${ssh_password}
      - ssh_hostname=${ssh_hostname}
      - ssh_port=${ssh_port}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - SSH=${SSH}
      - GCP_SA_KEY=${GCP_SA_KEY}
      - PROJECT_ID=${PROJECT_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_ACCOUNT=${GOOGLE_ACCOUNT}
      - SCHEMA=${SCHEMA}
      - GOOGLE_APP_PASS=${GOOGLE_APP_PASS}
      - SECRET_SALT=${SECRET_SALT}
      - DOCKER_USERNAME=${DOCKER_USERNAME}
    ports:
      - "8000:8000"
    restart: always

  mlcb_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/mlcb:frontend
    platform: linux/amd64
    environment:
      - DOCKER_USERNAME=${DOCKER_USERNAME}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mlcb_backend
    restart: always

networks:
  default:
    driver: bridge
