# pylint: disable=E1101,C0301,W0611
"""mlcbUpdate

Revision ID: 975af912aa7e
Revises: 
Create Date: 2024-01-27 14:19:47.260235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '975af912aa7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mlcb_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('Admin', 'User', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='mlcb'
    )
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='mlcb'
    )
    op.create_table('mlcb_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('participants', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('session_passcode', sa.String(length=100), nullable=True),
    sa.Column('is_call', sa.Boolean(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('session_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['mlcb.transcripts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['mlcb.mlcb_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='mlcb'
    )
    op.create_table('users_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('spoken_lang', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['mlcb.mlcb_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['mlcb.mlcb_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='mlcb'
    )

def downgrade() -> None:

    op.drop_table('users_session', schema='mlcb')
    op.drop_table('mlcb_sessions', schema='mlcb')
    op.drop_table('transcripts', schema='mlcb')
    op.drop_table('mlcb_users', schema='mlcb')
    # ### end Alembic commands ###
