# pylint: disable=E1101,C0301
"""session edit

Revision ID: a017c4be5a28
Revises: 4d9de57a362c
Create Date: 2023-12-27 22:45:55.054242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a017c4be5a28'
down_revision: Union[str, None] = '4d9de57a362c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='rtvt'
    )
    op.add_column('rtvt_sessions', sa.Column('participants', sa.ARRAY(sa.String()), nullable=False), schema='rtvt')
    op.add_column('rtvt_sessions', sa.Column('transcript_id', sa.Integer(), nullable=False), schema='rtvt')
    op.alter_column('rtvt_sessions', 'end_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               schema='rtvt')
    op.create_foreign_key(None, 'rtvt_sessions', 'transcripts', ['transcript_id'], ['id'], source_schema='rtvt', referent_schema='rtvt')
    op.drop_column('rtvt_sessions', 'start_at', schema='rtvt')
    op.drop_column('rtvt_sessions', 'transcript', schema='rtvt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rtvt_sessions', sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=False), schema='rtvt')
    op.add_column('rtvt_sessions', sa.Column('start_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False), schema='rtvt')
    op.drop_constraint(None, 'rtvt_sessions', schema='rtvt', type_='foreignkey')
    op.alter_column('rtvt_sessions', 'end_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               schema='rtvt')
    op.drop_column('rtvt_sessions', 'transcript_id', schema='rtvt')
    op.drop_column('rtvt_sessions', 'participants', schema='rtvt')

    op.drop_table('transcripts', schema='rtvt')
    # ### end Alembic commands ###
