# pylint: disable=E1101,C0301,W0611
"""users session init

Revision ID: eada31b694e9
Revises: d04d372d0ee8
Create Date: 2024-01-02 12:14:18.697447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eada31b694e9'
down_revision: Union[str, None] = 'd04d372d0ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('spoken_lang', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['rtvt.rtvt_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['rtvt.rtvt_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='rtvt'
    )

    # ### end Alembic commands ###


def downgrade() -> None:

    op.drop_table('users_session', schema='rtvt')
    # ### end Alembic commands ###
