name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -e 'backend/src'

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

    - name: Build Docker image
      run: |
        docker build -t your-image-name .
        docker tag your-image-name:latest your-image-name:$(date +%Y%m%d-%H%M%S)

    - name: Login to Docker Hub
      if: github.event_name == 'push'
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Push Docker image
      if: github.event_name == 'push'
      run: |
        docker push your-image-name
