name: RTVT CI/CD

on: [push]

env:
  IMAGE_TAG: $(date +%Y%m%d%H%M%S)

jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      GOOGLE_ACCOUNT: ${{ secrets.GOOGLE_ACCOUNT }}
      FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/mlcb:frontend
      BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/mlcb:backend
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Authenticate with Google Cloud
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
#
#      - name: Pull Docker Image from Docker Hub
#        run: |
#          docker pull ${{ env.FRONTEND_IMAGE }}
#
#      - name: Tag Docker Image for Google Container Registry
#        run: |
#          docker tag ${{ env.FRONTEND_IMAGE }} gcr.io/${{ env.PROJECT_ID }}/mlcb-frontend:latest
#
#      - name: Push Docker Image to Google Container Registry
#        run: |
#          docker push gcr.io/${{ env.PROJECT_ID }}/mlcb-frontend:latest
#
#      - name: Deploy Docker Image to Google Cloud Run
#        run: |
#          gcloud run deploy multilanguagechatbox \
#            --image=gcr.io/${{ env.PROJECT_ID }}/mlcb-frontend:latest \
#            --region=us-central1 \
#            --allow-unauthenticated \
#            --platform=managed

      - name: Deploy Backend
        run: |
          # Pull the Docker image from Docker Hub
          docker pull ${{ env.BACKEND_IMAGE }}
      
          # Tag the image for Google Container Registry
          docker tag ${{ env.BACKEND_IMAGE }} gcr.io/${{ env.PROJECT_ID }}/mlcb-backend:latest
      
          # Push the image to Google Container Registry
          docker push gcr.io/${{ env.PROJECT_ID }}/mlcb-backend:latest
      
          # Deploy the image to Google Cloud Run
          gcloud run deploy multilanguagechatboxbackend \
              --image=gcr.io/${{ env.PROJECT_ID }}/mlcb-backend:latest \
              --region=us-central1 \
              --allow-unauthenticated \
              --platform=managed \
              --port=8000 \
              --verbosity=debug \
              --set-env-vars=DB_HOST=${{ secrets.DB_HOST }},DB_PASS=${{ secrets.DB_PASS }},DB_PORT=${{ secrets.DB_PORT }},DB_USER=${{ secrets.DB_USER }},DB_NAME=${{ secrets.DB_NAME }},ssh_username=${{ secrets.ssh_username }},ssh_password=${{ secrets.ssh_password }},ssh_hostname=${{ secrets.ssh_hostname }},ssh_port=${{ secrets.ssh_port }},JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }},JWT_REFRESH_SECRET_KEY=${{ secrets.JWT_REFRESH_SECRET_KEY }},SSH=${{ secrets.SSH }},GOOGLE_CLOUD_PROJECT=${{ secrets.GOOGLE_CLOUD_PROJECT }},SCHEMA=${{ secrets.SCHEMA }},SECRET_SALT=${{ secrets.SECRET_SALT }},PROJECT_ID=${{ secrets.PROJECT_ID }},GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }},GOOGLE_ACCOUNT=${{ secrets.GOOGLE_ACCOUNT }}
          
